In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [4]:
url = 'https://www.worldometers.info/population/countries-in-asia-by-population/'
response = requests.get (url)
print(response)

<Response [200]>

In [6]:
soup = BeautifulSoup (response.text,'lxml')
print(soup.prettify()[:500])

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
 <!--<![endif]-->
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Asian Countries by Population (2025) - Worldometer
  </title>
  <meta content="List of countries (or dependencies) in Asia ranked by populat

In [18]:
table = soup.find ('table',id = 'example2')
headers = table.find_all ('th')
titles = []
for i in headers:
  title = i.text
  titles.append (title)

print(titles)

['#', 'Country (or dependency)', 'Population (2024)', 'Yearly Change', 'Net Change', 'Density (P/Km²)', 'Land Area (Km²)', 'Migrants (net)', 'Fert. Rate', 'Med. Age', 'Urban Pop %', 'World Share']

In [20]:
df = pd.DataFrame (columns = titles)
df

Empty DataFrame
Columns: [#, Country (or dependency), Population (2024), Yearly Change, Net Change, Density (P/Km²), Land Area (Km²), Migrants (net), Fert. Rate, Med. Age, Urban Pop %, World Share]
Index: []

In [32]:
rows = table.find_all ('tr')
for i in rows [1:]:
  data = i.find_all ('td')
  row = [tr.text.strip() for tr in data]
  l = len (df)
  df.loc [l] = row

df

,#,Country (or dependency),Population (2024),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,1,India,"1,450,935,791",0.89 %,"12,866,195",488,"2,973,190","-630,830",2.0,28,37 %,17.78 %
1,2,China,"1,419,321,278",-0.23 %,"-3,263,655",151,"9,388,211","-318,992",1.0,40,66 %,17.39 %
2,3,Indonesia,"283,487,931",0.82 %,"2,297,864",156,"1,811,570","-38,469",2.1,30,59 %,3.47 %
3,4,Pakistan,"251,269,164",1.52 %,"3,764,669",326,"770,880","-1,401,173",3.5,20,34 %,3.08 %
4,5,Bangladesh,"173,562,364",1.22 %,"2,095,374","1,333","130,170","-473,362",2.1,26,42 %,2.13 %
...,...,...,...,...,...,...,...,...,...,...,...,...
148,47,Cyprus,"1,358,282",0.99 %,"13,306",147,"9,240","8,138",1.4,38,61 %,0.02 %
149,48,Bhutan,"791,524",0.65 %,"5,139",21,"38,117",-277,1.4,30,49 %,0.01 %
150,49,Macao,"720,262",0.89 %,"6,350","24,009",30,"1,620",0.7,39,96 %,0.01 %
151,50,Maldives,"527,799",0.34 %,"1,805","1,759",300,"-2,421",1.6,32,39 %,0.01 %
152,51,Brunei,"462,721",0.82 %,"3,772",88,"5,270",0,1.7,32,80 %,0.01 %

In [36]:
df.to_csv(r"C:\Users\Administrator\OneDrive\Documents\WebscrapingFiles\Asian Countries by Population.csv",index = False)